### PR TITLE
Add slash syntax for AttrKey that parity with "in" syntax

### PR DESCRIPTION
**Pull request by dwijnand**

### CODE REVIEW

**Comment by dwijnand** [comment]
The Travis failure is spurious and I can't restart it.

**Comment by eed3si9n** [comment]
Value classes concern me. I don't think they add actual performance with JIT, but it's a bincompat hinderance.

**Comment by dwijnand** [comment]
Last commit dropped.

**Review by eed3si9n — APPROVED** [review]

**Comment by eed3si9n** [comment]
ok. let's do this.

**Pull request merged**
